version: '3.4'

services:
  python4:
    container_name: conda
    image: conda:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./course:/course