
services:
  python4:
    container_name: conda
    image: conda:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./course:/course
      - ./course/day3/face.dat:/root/.cache/scipy-data/face.dat